name: Run Stage 5 Tests

on:
  push:
    branches:
      - 'main'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10' 
            - run: |
                python -m unittest "./tests/hash_map_test.py"
